on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [master, main]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      isPush: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            r-lib/pkgdown
            nflverse/fastrmodels
            nflverse/nflplotR
            nflverse/nflreadr
            any::tidyverse
            any::ggrepel
            any::ggimage
            any::knitr
            any::tictoc
            any::ragg
            local::.
          needs: website

      - name: Build and deploy pkgdown site
        if: contains(env.isPush, 'true')
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Create website
        if: contains(env.isPush, 'false')
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      # - name: Create index file
      #   if: contains(env.isPush, 'false')
      #   run: |
      #     echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;URL=/dev/index.html" />  <script language="javascript"> window.location.replace('/dev/index.html')</script></head></html>' > ./docs/index.html

      - name: Deploy to Netlify
        if: contains(env.isPush, 'false')
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './docs'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          overwrites-pull-request-comment: true
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
        timeout-minutes: 1
